"""esquema inicial

Revision ID: 5bbde79adba9
Revises: 
Create Date: 2026-06-20 02:07:36.791511
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bbde79adba9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Date(), nullable=False),
    sa.Column('contador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dia', name='uq_ai_usage_user_dia')
    )
    op.create_index(op.f('ix_ai_usage_user_id'), 'ai_usage', ['user_id'], unique=False)
    op.create_table('bling_oauth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bling_oauth_token_user_id'), 'bling_oauth_token', ['user_id'], unique=True)
    op.create_table('nfe_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('desconto_tipo', sa.String(), nullable=False),
    sa.Column('desconto_valor', sa.Float(), nullable=False),
    sa.Column('remover_frete', sa.Boolean(), nullable=False),
    sa.Column('situacao_pendente', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfe_config_user_id'), 'nfe_config', ['user_id'], unique=True)
    op.create_table('precificacao_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('imposto', sa.Float(), nullable=False),
    sa.Column('cartao', sa.Float(), nullable=False),
    sa.Column('embalagem', sa.Float(), nullable=False),
    sa.Column('frete', sa.Float(), nullable=False),
    sa.Column('margem_padrao', sa.Float(), nullable=False),
    sa.Column('canais', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precificacao_config_user_id'), 'precificacao_config', ['user_id'], unique=True)
    op.create_table('radar_alvo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radar_alvo_sku'), 'radar_alvo', ['sku'], unique=False)
    op.create_index(op.f('ix_radar_alvo_user_id'), 'radar_alvo', ['user_id'], unique=False)
    op.create_table('radar_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alvo_id', sa.Integer(), nullable=False),
    sa.Column('preco_normal', sa.Float(), nullable=True),
    sa.Column('preco_oferta', sa.Float(), nullable=True),
    sa.Column('coletado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alvo_id'], ['radar_alvo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radar_snapshot_alvo_id'), 'radar_snapshot', ['alvo_id'], unique=False)
    op.create_index(op.f('ix_radar_snapshot_coletado_em'), 'radar_snapshot', ['coletado_em'], unique=False)
    op.create_index(op.f('ix_radar_snapshot_user_id'), 'radar_snapshot', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_radar_snapshot_user_id'), table_name='radar_snapshot')
    op.drop_index(op.f('ix_radar_snapshot_coletado_em'), table_name='radar_snapshot')
    op.drop_index(op.f('ix_radar_snapshot_alvo_id'), table_name='radar_snapshot')
    op.drop_table('radar_snapshot')
    op.drop_index(op.f('ix_radar_alvo_user_id'), table_name='radar_alvo')
    op.drop_index(op.f('ix_radar_alvo_sku'), table_name='radar_alvo')
    op.drop_table('radar_alvo')
    op.drop_index(op.f('ix_precificacao_config_user_id'), table_name='precificacao_config')
    op.drop_table('precificacao_config')
    op.drop_index(op.f('ix_nfe_config_user_id'), table_name='nfe_config')
    op.drop_table('nfe_config')
    op.drop_index(op.f('ix_bling_oauth_token_user_id'), table_name='bling_oauth_token')
    op.drop_table('bling_oauth_token')
    op.drop_index(op.f('ix_ai_usage_user_id'), table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
