"""tabela oauth_state

Revision ID: a43c5a102dc8
Revises: 5bbde79adba9
Create Date: 2026-06-20 22:36:19.171591
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43c5a102dc8'
down_revision: Union[str, None] = '5bbde79adba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_state',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_index(op.f('ix_oauth_state_user_id'), 'oauth_state', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_state_user_id'), table_name='oauth_state')
    op.drop_table('oauth_state')
    # ### end Alembic commands ###
